export const adminSkillGapProgramData = [
  {
    userId: 'U001',
    name: 'John Doe',
    email: 'johndoe@example.com',
    date: '12-07-2024',
    program: 'Front-end Developer',
    status: 'Pending',
  },
  {
    userId: 'U002',
    name: 'Jane Smith',
    email: 'janesmith@example.com',
    date: '12-07-2024',
    program: 'Front-end Developer',
    status: 'Accepted',
  },
  {
    userId: 'U003',
    name: 'Michael Johnson',
    email: 'michaelj@example.com',
    date: '12-07-2024',
    program: 'Back-end Developer',
    status: 'Rejected',
  },
  {
    userId: 'U004',
    name: 'Emily Davis',
    email: 'emilyd@example.com',
    date: '12-07-2024',
    program: 'Front-end Developer',
    status: 'Pending',
  },
  {
    userId: 'U005',
    name: 'Chris Brown',
    email: 'chrisb@example.com',
    date: '12-07-2024',
    program: 'Dev ops Technician',
    status: 'Pending',
  },
];
